name: code checking

on: [push]

jobs:
  build:
    name: code checking
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Get lynx
        uses: sudo apt-get install lynx -y
      - name: Check code
        run: |
        ./gradlew pmdMain
        if [[ $? -eq 1 ]]; then
          lynx build/reports/pmd/main.html -dump
        fi
      - name: Check tests
        run: |
        ./gradlew pmdTest
        if [[ $? -eq 1 ]]; then
          lynx build/reports/pmd/test.html -dump
        fi