name: code checking

on: [push]

jobs:
  build:
    name: code checking
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Get lynx
        run: sudo apt-get install lynx -y
      - name: Prepare gradlew for execution
        run: chmod +x gradlew
      - name: Check code
        run: ./gradlew pmdMain; if [[ $? -ne 0 ]]; then lynx build/reports/pmd/main.html -dump; fi
      - name: Check tests
        if: success() || failure()
        run: ./gradlew pmdTest; if [[ $? -ne 0 ]]; then lynx build/reports/pmd/test.html -dump; fi