name: code checking

on: [push]

jobs:
  build:
    name: code checking
    runs-on: ubuntu-latest
    steps:
      - uses: sfdx-actions/setup-pmd@v1
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: run-pmd
        run: pmd -d ./src -R category/apex/design.xml -f text