name: code coverage

on: [push]

jobs:
  build:
    name: code coverage
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Generate jacocotest.exec
        run: |
        ./gradlew test
        ls build/jacoco/jacocoTest.exec
      - name: Check coverage
        run: |
        ./gradlew jacocoTestCoverageVerification